# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - qa/*
  - dev/*
  - refs/pull/*

resources:
    repositories:
      - repository: python_base_template
        type: git
        name: Personal Projects/pipeline_base_templates

extends:
  template: python.yaml@python_base_template


#pool:
#  vmImage: ubuntu-latest
#
#steps:
#  - task: UsePythonVersion@0
#    inputs:
#      versionSpec: '3.9'
#      addToPath: true
#      architecture: 'x64'
#  - task: Npm@1
#    inputs:
#      command: 'custom'
#      customCommand: 'install -g serverless@latest'
#  - task: Bash@3
#    inputs:
#      targetType: 'inline'
#      script: |
#        export AWS_ACCESS_KEY_ID=$(aws_access_key_id)
#        export AWS_SECRET_ACCESS_KEY=$(aws_secret_access_key)
#        export SLS_DEBUG=true
#
#        ls
#
#
#        printenv | grep AWS
#
#        serverless plugin install -n serverless-python-requirements
#
#        serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
#
#        serverless deploy --verbose