trigger:
  - container

resources:
    repositories:
      - repository: templates
        type: git
        name: Personal Projects/pipeline_base_templates



extends:
  template: python.yml@templates
  parameters:
    repository: fastapi_template