trigger:
- azure-pipelines
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    echo Hello, world!
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Run dependencies"
- script: |
    echo Finished!
  displayName: "Run Finished"

