# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - qa
  - qa/*
  - dev
  - dev/*
  - refs/pull/*

resources:
    repositories:
      - repository: templates
        type: git
        name: Personal Projects/pipeline_base_templates



extends:
  template: python.yml@templates
  parameters:
    repository: fastapi_template

